# Generated by Django 4.2.5 on 2023-10-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mynotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotes',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='file',
            field=models.FileField(default='', upload_to='myFiles'),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='option',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
